import {
  ArrowLeft,
  CheckCircle2,
  Clock3,
  Download,
  Sparkles
} from "lucide-react";

import {
  Link,
  useNavigate,
  useSearchParams
} from "react-router-dom";

import { useEffect, useState } from "react";

const API_URL = "https://ai-powered-personal-diet-planner-with.onrender.com";

function PlanResult() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const [plan, setPlan] = useState(null);
  const [source, setSource] = useState("unknown");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    loadPlan();
  }, []);

  async function loadPlan() {
    const token = localStorage.getItem("access_token");

    if (!token) {
      navigate("/login");
      return;
    }

    const planId = searchParams.get("id");

    /*
      If an ID exists in the URL, this page was opened
      from Saved Plans.

      Example:
      /plan-result?id=PLAN_ID
    */

    if (planId) {
      try {
        const response = await fetch(
          `${API_URL}/api/plans/${planId}`,
          {
            headers: {
              Authorization: `Bearer ${token}`
            }
          }
        );

        const data = await response.json();

        if (!response.ok) {
          throw new Error(
            data.error || "Unable to load saved plan."
          );
        }

        setPlan(data.plan);
        setSource("saved_plan");
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }

      return;
    }

    /*
      If there is no ID, load the newly generated plan
      from sessionStorage.
    */

    const savedPlan = sessionStorage.getItem(
      "generated_plan"
    );

    const savedSource = sessionStorage.getItem(
      "plan_source"
    );

    if (!savedPlan) {
      navigate("/generate-plan");
      return;
    }

    try {
      setPlan(JSON.parse(savedPlan));
      setSource(savedSource || "unknown");
    } catch {
      navigate("/generate-plan");
    } finally {
      setLoading(false);
    }
  }

  function downloadPlan() {
    if (!plan) {
      return;
    }

    const content = `
NUTRIAI — PERSONAL DIET PLAN

Breakfast
${plan.breakfast}

Lunch
${plan.lunch}

Snack
${plan.snack}

Dinner
${plan.dinner}

Nutrition Summary
${plan.nutrition_summary}

Generated by NutriAI.

Educational/general wellness example — not medical advice.
    `.trim();

    const blob = new Blob(
      [content],
      {
        type: "text/plain"
      }
    );

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download = "nutriai-diet-plan.txt";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  }

  if (loading) {
    return (
      <div className="dashboard-loading">

        <div className="loading-spinner"></div>

        <h2>
          Loading your plan...
        </h2>

        <p>
          Fetching your nutrition plan.
        </p>

      </div>
    );
  }

  if (error) {
    return (
      <div className="dashboard-loading">

        <h2>
          Unable to load plan
        </h2>

        <p>
          {error}
        </p>

        <Link
          to="/saved-plans"
          className="btn btn-primary"
        >
          Back to saved plans
        </Link>

      </div>
    );
  }

  if (!plan) {
    return (
      <div className="dashboard-loading">

        <h2>
          No plan found
        </h2>

        <Link
          to="/generate-plan"
          className="btn btn-primary"
        >
          Generate a plan
        </Link>

      </div>
    );
  }

  return (
    <div className="result-page">

      <div className="result-container">

        <Link
          to="/dashboard"
          className="auth-back"
        >
          <ArrowLeft size={17} />
          Back to dashboard
        </Link>


        {/* HEADER */}

        <header className="result-header">

          <div>

            <div className="result-title-row">

              <div className="result-title-icon">
                <Sparkles size={22} />
              </div>

              <div>

                <p className="dashboard-overline">
                  PERSONALIZED PLAN
                </p>

                <h1>
                  Your nutrition plan
                </h1>

              </div>

            </div>

            <p className="result-description">
              Here's your generated general wellness meal
              plan based on the information in your profile.
            </p>

          </div>


          <button
            className="btn btn-outline"
            onClick={downloadPlan}
          >
            <Download size={17} />
            Download
          </button>

        </header>


        {/* SOURCE STATUS */}

        <div className="result-status">

          <CheckCircle2 size={18} />

          <div>

            <strong>
              Plan loaded successfully
            </strong>

            <span>

              {source === "ai_api"
                ? "Generated using the configured AI API."
                : source === "saved_plan"
                  ? "Retrieved securely from your saved cloud plans."
                  : "Generated using the local fallback engine."}

            </span>

          </div>

        </div>


        {/* MEALS */}

        <section className="result-meals">

          <MealCard
            icon="☀️"
            meal="Breakfast"
            title={plan.breakfast}
          />

          <MealCard
            icon="🥗"
            meal="Lunch"
            title={plan.lunch}
          />

          <MealCard
            icon="🍎"
            meal="Snack"
            title={plan.snack}
          />

          <MealCard
            icon="🌙"
            meal="Dinner"
            title={plan.dinner}
          />

        </section>


        {/* NUTRITION SUMMARY */}

        <section className="nutrition-summary">

          <div className="summary-icon">
            <Clock3 size={20} />
          </div>

          <div>

            <p className="panel-label">
              NUTRITION SUMMARY
            </p>

            <h2>
              Daily overview
            </h2>

            <p>
              {plan.nutrition_summary}
            </p>

          </div>

        </section>


        {/* ACTIONS */}

        <div className="result-actions">

          <Link
            to="/generate-plan"
            className="btn btn-outline"
          >
            <Sparkles size={17} />
            Generate another
          </Link>


          <Link
            to="/saved-plans"
            className="btn btn-primary"
          >
            View saved plans
          </Link>

        </div>


        {/* DISCLAIMER */}

        <p className="result-disclaimer">
          NutriAI provides educational/general wellness
          meal-planning examples and is not a substitute for
          professional medical or nutritional advice.
        </p>

      </div>

    </div>
  );
}


/* MEAL CARD */

function MealCard({
  icon,
  meal,
  title
}) {
  return (
    <article className="result-meal-card">

      <div className="result-meal-icon">
        {icon}
      </div>

      <div className="result-meal-content">

        <p>
          {meal}
        </p>

        <h2>
          {title}
        </h2>

      </div>

    </article>
  );
}


export default PlanResult;